steps:
  - name: python:3.10-slim
    entrypoint: pip
    args: [ "install", "-r", "requirements.txt", "--user" ]
    id: Install dependencies
  - name: python:3.10-slim
    entrypoint: python
    args: [ "-m", "pytest", "--junitxml=${SHORT_SHA}_test_log.xml" ]
    id: Run unit tests
  - name: 'gcr.io/cloud-builders/gsutil'
    args: [ '-m', 'cp', '-r', 'gs://book-recommender-model-saves/$_MODEL_VERSION', '.' ]
    id: Download model files
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '--build-arg'
      - 'MODEL_FILES="$_MODEL_VERSION"'
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - .
      - '-f'
      - Dockerfile
    id: Build
#  - name: gcr.io/cloud-builders/docker
#    args:
#      - push
#      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
#    id: Push
#  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
#    args:
#      - run
#      - services
#      - update
#      - $_SERVICE_NAME
#      - '--platform=managed'
#      - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
#      - >-
#        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
#      - '--region=$_DEPLOY_REGION'
#      - '--quiet'
#    id: Deploy
#    entrypoint: gcloud
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _PLATFORM: managed
  _SERVICE_NAME: book-recommender-collab-nn
  _TRIGGER_ID: eee6c1dd-9d14-45af-ba1a-b56d0d55c1cc
  _DEPLOY_REGION: us-east1
  _GCR_HOSTNAME: us.gcr.io
  _MODEL_VERSION: "1672594012"
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - book-recommender-collab-nn
